import React from 'react';
import { Search, Leaf, MessageCircle, BarChart3, ClipboardPlus, Bot, TrendingUp, Users, Award } from 'lucide-react';

const Home: React.FC = () => {
  const features = [
    {
      icon: Search,
      title: 'AI Symptoms Checker',
      description: 'Advanced AI-powered symptom analysis to help identify potential health conditions with high accuracy.',
      color: 'from-blue-500 to-blue-600'
    },
    {
      icon: Leaf,
      title: 'Natural Remedies',
      description: 'Evidence-based natural remedies for common health conditions, generated by our intelligent AI system.',
      color: 'from-green-500 to-green-600'
    },
    {
      icon: MessageCircle,
      title: 'Patient Chat Assistant',
      description: 'Get instant, personalized answers to your health questions from our advanced AI assistant.',
      color: 'from-purple-500 to-purple-600'
    },
    {
      icon: BarChart3,
      title: 'Health Analytics',
      description: 'Visualize and track your health metrics with intelligent insights and trend analysis.',
      color: 'from-orange-500 to-orange-600'
    },
    {
      icon: ClipboardPlus,
      title: 'Treatment Plans',
      description: 'Personalized, comprehensive treatment recommendations based on your specific health profile.',
      color: 'from-red-500 to-red-600'
    },
    {
      icon: Bot,
      title: 'Advanced AI Technology',
      description: 'Powered by state-of-the-art machine learning models for accurate medical insights and recommendations.',
      color: 'from-indigo-500 to-indigo-600'
    }
  ];

  const stats = [
    { icon: Users, label: 'Users Helped', value: '50,000+', change: '+2,500' },
    { icon: Search, label: 'Health Conditions', value: '10,000+', change: '+500' },
    { icon: Leaf, label: 'Natural Remedies', value: '2,500+', change: '+150' },
    { icon: Award, label: 'Accuracy Rate', value: '95%', change: '+2%' }
  ];

  return (
    <div className="space-y-12">
      {/* Welcome Section */}
      <div className="text-center">
        <h2 className="text-3xl font-bold text-gray-800 mb-4">
          Welcome to the Future of Healthcare
        </h2>
        <p className="text-lg text-gray-600 max-w-3xl mx-auto">
          Experience intelligent healthcare assistance with our comprehensive AI-powered platform. 
          Get personalized health insights, natural remedies, and expert guidance at your fingertips.
        </p>
      </div>

      {/* Features Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {features.map((feature, index) => {
          const Icon = feature.icon;
          return (
            <div
              key={index}
              className="bg-white rounded-2xl p-6 shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2 border border-gray-100"
            >
              <div className={`w-12 h-12 rounded-xl bg-gradient-to-r ${feature.color} flex items-center justify-center mb-4`}>
                <Icon className="text-white" size={24} />
              </div>
              <h3 className="text-xl font-semibold text-gray-800 mb-3">
                {feature.title}
              </h3>
              <p className="text-gray-600 leading-relaxed">
                {feature.description}
              </p>
            </div>
          );
        })}
      </div>

      {/* Statistics Section */}
      <div className="bg-white rounded-2xl p-8 shadow-lg">
        <h3 className="text-2xl font-bold text-center text-gray-800 mb-8">
          Platform Impact & Statistics
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {stats.map((stat, index) => {
            const Icon = stat.icon;
            return (
              <div key={index} className="text-center">
                <div className="flex justify-center mb-3">
                  <div className="w-12 h-12 rounded-full bg-gradient-to-r from-blue-500 to-purple-500 flex items-center justify-center">
                    <Icon className="text-white" size={20} />
                  </div>
                </div>
                <div className="text-3xl font-bold text-gray-800 mb-1">
                  {stat.value}
                </div>
                <div className="text-sm text-gray-600 mb-1">
                  {stat.label}
                </div>
                <div className="text-sm text-green-600 font-medium">
                  {stat.change}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Call to Action */}
      <div className="bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl p-8 text-white text-center">
        <h3 className="text-2xl font-bold mb-4">
          Ready to Transform Your Healthcare Experience?
        </h3>
        <p className="text-lg mb-6 opacity-90">
          Start exploring our AI-powered health tools and take control of your wellness journey today.
        </p>
        <div className="flex flex-wrap justify-center gap-4">
          <button className="bg-white text-blue-600 px-6 py-3 rounded-xl font-semibold hover:bg-gray-100 transition-colors duration-200">
            Check Symptoms
          </button>
          <button className="border-2 border-white text-white px-6 py-3 rounded-xl font-semibold hover:bg-white hover:text-blue-600 transition-colors duration-200">
            Chat with AI
          </button>
        </div>
      </div>
    </div>
  );
};

export default Home;